# Monitor Rules
#Main Desktop monitor
monitorrule=name:eDP-1,width:3072,height:1920,refresh:120,x:0,y:0,scale:2,vrr:1,rr:0

#Second Temporary monitor (projector, ...)
monitorrule=name:HDMI-A-1,width:1920,height:1080,refresh:60,x:3072,y:0,scale:2
