# Window Rules

#Main Menu
windowrule=isfloating:1,appid:impala
windowrule=isfloating:1,appid:bluetui

windowrule=noswallow:1,appid:^com.gabm.satty$
windowrule=isfullscreen:1,appid:^com.gabm.satty$
windowrule=animation_type_open:none,appid:^com.gabm.satty$
windowrule=animation_type_close:none,appid:^com.gabm.satty$
windowrule=isoverlay:1,appid:^com.gabm.satty$
windowrule=isfloating:1,appid:^com.gabm.satty$


#Layer Rules
layerrule=noblur:1,noanim:1,layer_name:selection

