# wallust v3.5
# Global section - values below can be overwritten by command line flags
# How the image is parse, in order to get the colors:
backend = "resized" # full - resized - wal - thumb -  fastresize - kmeans
# What color space to use to produce and select the most prominent colors:
color_space = "labmixed" # lab - labmixed - lch - lchmixed - salience

# Use the most prominent colors in a way that makes sense, a scheme color palette:
# dark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
# saliencedark - saliencedarkbalanced - saliencedarkdistributed - saliencedarklow (each has the 16 variations)
# salienceligh - saliencelightbalanced - saliencelightdistributed - saliencelightlow (each has the 16 variations)
palette = "saliencedarkbalanced"

check_contrast = true

alpha = 85

[templates]
pallete = {
    template = 'pallete/pallete.md',
    target = '~/.nixfiles/config/palette.md',
}

mango = {
    template = 'mango/style.conf',
    target = '~/.nixfiles/config/mango/style.conf',
}

mangobar = {
    template = 'mangobar/style.css',
    target = '~/.nixfiles/config/mangobar/style.css',
}

foot = {
    template = 'foot/colors.ini',
    target = '~/.nixfiles/config/foot/colors.ini',
}

mako = {
    template = 'mako/config',
    target = '~/.nixfiles/config/mako/config',
}

gtk-3 = {
    template = 'gtk/gtk.css',
    target = '~/.nixfiles/config/gtk-3.0/gtk.css',
}

gtk-4 = {
    template = 'gtk/gtk.css',
    target = '~/.nixfiles/config/gtk-4.0/gtk.css',
}

[hooks]
mango = "mmsg dispatch reload_config"
mangobar = "pkill mangobar && mangobar >/dev/null 2>&1 &"
mako = "pkill mako"

