[general]
# This sets the default directory and filename format for the Save button
output-filename = "~/Pictures/Screenshots/screenshot-%Y-%m-%d_%H:%M:%S.png"

# Automatically close the application right after you click Copy or Save
early-exit = true

# Explicitly set the Wayland clipboard command to ensure copies work reliably
copy-command = "wl-copy"

#Go fullscreen when launch
fullscreen = true
